#!/usr/bin/env ruby

config = [{gem: 'httparty', ver: '~> 0.13.7'}, {gem: 'geoip', ver: '~> 0.0.1'}]
config.each do |item|
  gem_name, *gem_ver_reqs = item[:gem], item[:ver]
  gdep = Gem::Dependency.new(gem_name, *gem_ver_reqs)
  found_gspec = gdep.matching_specs.max_by(&:version)
  if found_gspec && !found_gspec.nil?
    puts "gem required found #{gdep}... continue\n\n"
  else
    abort "Requirement '#{gdep}' not satisfied; install gem please...\n\n"
#    return false
#    abort
  end
end

require "httparty"
require "geoip"
require_relative "Response"

if ARGV[0] == "get" && ARGV[1].to_s.length > 0
  geo= GeoIp.new(ARGV[1].to_s, Response.new)
  geo.get
  p geo
else
  puts "wrong argumrnts!!!"
end
