#!/usr/bin/env ruby

require_relative "geoip"
require_relative "Response"

if ARGV[0] == "get" && ARGV[1].to_s.length > 0
  geo= GeoIp.new(ARGV[1].to_s, Response.new)
  geo.get
  p geo
else
  puts "wrong argumrnts!!!"
end
